export enum colorPalette {
  lightColor = '#B0F4E6',
  accentColor = '#12D3CF',
  heavyColor = '#OD4C92',
  grayColor = '#cecece',
  basicTextColor = '#333',
  whiteColor = '#fff',
  grayTextColor = '#777',
  lightGrayTextColor = '#BABABA',
  borderColor = '#CBCBCB',
  tagColor = '#74D4E4',
  modalIconColor = '#D0E2Ef',
  modalCancelButtonColor = '#CDDBF0',
  itemCardHeartColor = '#DEDEDE',
}
