export enum colorPalette {
  lightColor = '#B0F4E6',
  accentColor = '#12D3CF',
  heavyColor = '#0D4C92',
  deepMintColor = '#3AA6B9',
  grayColor = '#cecece',
  basicTextColor = '#333',
  whiteColor = '#fff',
  grayTextColor = '#777',
  lightGrayTextColor = '#BABABA',
  borderColor = '#CBCBCB',
  headerSearchColor = '#f1f1f1',
  tagColor = '#74D4E4',
  modalIconColor = '#D0E2Ef',
  modalCancelButtonColor = '#CDDBF0',
  itemCardHeartColor = '#DEDEDE',
  selectListHoverColor = '#F2F7FF',
  loadingColor = '#00ffcc',
}
